mv scatter_adj.all.html adj.all.html
mv scatter_adj.pert.html adj.pert.html
mv scatter_adj.ppl.html adj.ppl.html
mv scatter_adv.all.html adv.all.html
mv scatter_noun.act.html noun.act.html
mv scatter_noun.animal.html noun.animal.html
mv scatter_noun.artifact.html noun.artifact.html
mv scatter_noun.attribute.html noun.attribute.html
mv scatter_noun.body.html noun.body.html
mv scatter_noun.cognition.html noun.cognition.html
mv scatter_noun.communication.html noun.communication.html
mv scatter_noun.event.html noun.event.html
mv scatter_noun.feeling.html noun.feeling.html
mv scatter_noun.food.html noun.food.html
mv scatter_noun.group.html noun.group.html
mv scatter_noun.location.html noun.location.html
mv scatter_noun.motive.html noun.motive.html
mv scatter_noun.object.html noun.object.html
mv scatter_noun.person.html noun.person.html
mv scatter_noun.phenomenon.html noun.phenomenon.html
mv scatter_noun.plant.html noun.plant.html
mv scatter_noun.possession.html noun.possession.html
mv scatter_noun.process.html noun.process.html
mv scatter_noun.quantity.html noun.quantity.html
mv scatter_noun.relation.html noun.relation.html
mv scatter_noun.shape.html noun.shape.html
mv scatter_noun.state.html noun.state.html
mv scatter_noun.substance.html noun.substance.html
mv scatter_noun.time.html noun.time.html
mv scatter_noun.Tops.html noun.Tops.html
mv scatter_verb.body.html verb.body.html
mv scatter_verb.change.html verb.change.html
mv scatter_verb.cognition.html verb.cognition.html
mv scatter_verb.communication.html verb.communication.html
mv scatter_verb.competition.html verb.competition.html
mv scatter_verb.consumption.html verb.consumption.html
mv scatter_verb.contact.html verb.contact.html
mv scatter_verb.creation.html verb.creation.html
mv scatter_verb.emotion.html verb.emotion.html
mv scatter_verb.motion.html verb.motion.html
mv scatter_verb.perception.html verb.perception.html
mv scatter_verb.possession.html verb.possession.html
mv scatter_verb.social.html verb.social.html
mv scatter_verb.stative.html verb.stative.html
mv scatter_verb.weather.html verb.weather.html
